baseURL = 'https://tpcad.github.io/'
languageCode = 'zh-CN'
title = 'Eulamber'
theme = "hugo-PaperMod"

[params]
env = "production"
title = "Eulamber"
description = "TPCAD's blog"
author = "TPCAD"

showBreadCrumbs = true
ShowCodeCopyButtons = true
UseHugoToc = true
disableScrollToTop = false
showtoc = true
social = true

[params.homeInfoParams]
Title = "æ„¿çƒ­æƒ…åœ¨é£ä¸­æ°¸ä¸ç†„ç­"
Content = "Hi there ğŸ‘‹. Welcome to my blog"

# [[params.socialIcons]]
# name = "github"
# title = "Github Profile"
# url = "https://github.com/tpcad"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
name = "Archive"
url = "archives"
weigaht = 5

[[menu.main]]
name = "Search"
url = "search/"
weigaht = 10

[[menu.main]]
name = "Tags"
url = "tags/"
weigaht = 10

[outputs]
home = ["HTML", "RSS", "JSON"]
