baseURL = 'https://tpcad.github.io/tpcad-blog'
languageCode = 'zh-CN'
title = 'Eulamber'
theme = "hugo-PaperMod"

[params]
env = "production"
title = "Eulamber"
description = "TPCAD's blog"
author = "TPCAD"

showBreadCrumbs = true
ShowCodeCopyButtons = true
UseHugoToc = true
disableScrollToTop = false
showtoc = true
social = true

[params.homeInfoParams]
Title = "æ„¿çƒ­æƒ…åœ¨é£ä¸­æ°¸ä¸ç†„ç­"
Content = "Hi ğŸ‘‹. æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ã€‚å‘ç°æ–‡ç« æœ‰ä»»ä½•é—®é¢˜éƒ½å¯ä»¥åœ¨ Github ä¸­æäº¤ Issueï¼ˆç‚¹å‡»ä¸‹é¢çš„å›¾æ ‡å³å¯è·³è½¬ï¼‰ã€‚"

[[params.socialIcons]]
name = "github"
title = "Blog Repo"
url = "https://github.com/TPCAD/tpcad-blog/issues"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
name = "Archive"
url = "archives"
weigaht = 5

[[menu.main]]
name = "Search"
url = "search/"
weigaht = 10

[[menu.main]]
name = "Tags"
url = "tags/"
weigaht = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.highlight]
style = 'catppuccin-frappe'
